### ISSUE TITLE
OutOfMemory crash - Windows 10 x64

### ISSUE THREAD

**Issue by theharleyquin** [rwood/WallpaperChange#10]
App was working great on Win10 then suddenly began throwing OOM errors. System has 16 GB so memory isn't the issue and other apps have no issues. 

Version=1
EventType=CLR20r3
EventTime=130925063703603399
ReportType=2
Consent=1
UploadTime=130925063704203801
ReportIdentifier=17e9d247-8f9a-11e5-9bf6-448a5b64cc77
Response.BucketId=9c8bf0e7fa076921426392723abb0c4f
Response.BucketTable=5
Response.LegacyBucketId=128915169921
Response.type=4
Sig[0].Name=Problem Signature 01
Sig[0].Value=wallpaperchange.exe
Sig[1].Name=Problem Signature 02
Sig[1].Value=1.0.0.0
Sig[2].Name=Problem Signature 03
Sig[2].Value=54750a5d
Sig[3].Name=Problem Signature 04
Sig[3].Value=System.Drawing
Sig[4].Name=Problem Signature 05
Sig[4].Value=2.0.0.0
Sig[5].Name=Problem Signature 06
Sig[5].Value=55960f2e
Sig[6].Name=Problem Signature 07
Sig[6].Value=144
Sig[7].Name=Problem Signature 08
Sig[7].Value=61
Sig[8].Name=Problem Signature 09
Sig[8].Value=System.OutOfMemoryException
DynamicSig[1].Name=OS Version
DynamicSig[1].Value=10.0.10240.2.0.0.256.4
DynamicSig[2].Name=Locale ID
DynamicSig[2].Value=1033
UI[2]=C:\Users\Kyle\Downloads\WallpaperChange_0.8\WallpaperChange.exe
UI[3]=WallpaperChange has stopped working
UI[4]=Windows can check online for a solution to the problem.
UI[5]=Check online for a solution and close the program
UI[6]=Check online for a solution later and close the program
UI[7]=Close the program
LoadedModule[0]=C:\Users\Kyle\Downloads\WallpaperChange_0.8\WallpaperChange.exe
LoadedModule[1]=C:\Windows\SYSTEM32\ntdll.dll
LoadedModule[2]=C:\Windows\SYSTEM32\MSCOREE.DLL
LoadedModule[3]=C:\Windows\system32\KERNEL32.dll
LoadedModule[4]=C:\Windows\system32\KERNELBASE.dll
LoadedModule[5]=C:\Windows\system32\apphelp.dll
LoadedModule[6]=C:\Windows\system32\ADVAPI32.dll
LoadedModule[7]=C:\Windows\system32\msvcrt.dll
LoadedModule[8]=C:\Windows\system32\sechost.dll
LoadedModule[9]=C:\Windows\system32\RPCRT4.dll
LoadedModule[10]=C:\Windows\Microsoft.NET\Framework64\v4.0.30319\mscoreei.dll
LoadedModule[11]=C:\Windows\system32\SHLWAPI.dll
LoadedModule[12]=C:\Windows\system32\combase.dll
LoadedModule[13]=C:\Windows\system32\GDI32.dll
LoadedModule[14]=C:\Windows\system32\USER32.dll
LoadedModule[15]=C:\Windows\system32\IMM32.DLL
LoadedModule[16]=C:\Windows\system32\MSCTF.dll
LoadedModule[17]=C:\Windows\system32\kernel.appcore.dll
LoadedModule[18]=C:\Windows\SYSTEM32\VERSION.dll
LoadedModule[19]=C:\Windows\Microsoft.NET\Framework64\v2.0.50727\mscorwks.dll
LoadedModule[20]=C:\Windows\WinSxS\amd64_microsoft.vc80.crt_1fc8b3b9a1e18e3b_8.0.50727.9185_none_88e323712fabe0b2\MSVCR80.dll
LoadedModule[21]=C:\Windows\system32\shell32.dll
LoadedModule[22]=C:\Windows\system32\windows.storage.dll
LoadedModule[23]=C:\Windows\system32\shcore.dll
LoadedModule[24]=C:\Windows\system32\powrprof.dll
LoadedModule[25]=C:\Windows\system32\profapi.dll
LoadedModule[26]=C:\Windows\assembly\NativeImages_v2.0.50727_64\mscorlib\7ee8db5b2648fb3da2a931b409554e5d\mscorlib.ni.dll
LoadedModule[27]=C:\Windows\system32\ole32.dll
LoadedModule[28]=C:\Windows\SYSTEM32\bcryptPrimitives.dll
LoadedModule[29]=C:\Windows\system32\uxtheme.dll
LoadedModule[30]=C:\Windows\Microsoft.NET\Framework64\v2.0.50727\mscorjit.dll
LoadedModule[31]=C:\Windows\assembly\NativeImages_v2.0.50727_64\System\642d932e359f667bad16bdbfbdb0ed7f\System.ni.dll
LoadedModule[32]=C:\Windows\assembly\NativeImages_v2.0.50727_64\System.Drawing\8cca688b0ce3a28d1c27ab8dfa0a5589\System.Drawing.ni.dll
LoadedModule[33]=C:\Windows\assembly\NativeImages_v2.0.50727_64\System.Windows.Forms\dd7270659543a747884a5a1a44d33dcd\System.Windows.Forms.ni.dll
LoadedModule[34]=C:\Windows\system32\dwmapi.dll
LoadedModule[35]=C:\Windows\WinSxS\amd64_microsoft.windows.gdiplus_6595b64144ccf1df_1.1.10240.16384_none_89a94c179af51f83\gdiplus.dll
LoadedModule[36]=C:\Windows\SYSTEM32\DWrite.dll
LoadedModule[37]=C:\Windows\assembly\NativeImages_v2.0.50727_64\System.Configuration\dd10cececdeef026fb470c736bebc180\System.Configuration.ni.dll
LoadedModule[38]=C:\Windows\assembly\NativeImages_v2.0.50727_64\System.Xml\fd04c87759f44ebc88d2bb4a31e61a97\System.Xml.ni.dll
LoadedModule[39]=C:\Windows\SYSTEM32\ntmarta.dll
State[0].Key=Transport.DoneStage1
State[0].Value=1
FriendlyEventName=Stopped working
ConsentKey=CLR20r3
AppName=WallpaperChange
AppPath=C:\Users\Kyle\Downloads\WallpaperChange_0.8\WallpaperChange.exe
ReportDescription=Stopped working
ApplicationIdentity=00000000000000000000000000000000

**Comment by rwood** [comment]
Should be fixed now.
