### ISSUE TITLE
Applications crash's and closes without errors on Wallpaper change

### ISSUE THREAD

**Issue by Stevesno** [rwood/WallpaperChange#5]
Windows 8 x64

Everytime it comes to the time to change the wallpaper, it crashes after setting it.

0.8

**Comment by goldenpipes** [comment]
Still Happening i went ahead and made windows just manage it with the control panel.

**Comment by theharleyquin** [comment]
Do you mean you just set as wallpaper? No rotating?

**Comment by rwood** [comment]
I have to apologize for ignoring this project.  Life gets in the way of things.  I know it's been a long time, but I had some time this last weekend and rewrote a good portion of the app.  It should solve the problem.
