### ISSUE TITLE
Windows slow logon bug

### ISSUE THREAD

**Issue by alxglover** [rwood/WallpaperChange#7]
Hi,

There is a bug in Windows (I'm using 7) relating to having a solid colour as a background, it causes logon to be slow (up to 30 secs). There is a hotfix: http://support.microsoft.com/kb/977346 however it doesn't seem to want to install for me and suggested workarounds don't help.

The problem is that after a couple of reboots, the WallpaperChange program appears to remove the existing wallpaper leaving the solid colour background. Since the program only starts up and sets the wallpaper after logon, the placeholder background causes the slow logon issue. If the program could always leave the last wallpaper background image alone before replacing it with the appropriate image according to the config, I think that would solve the problem.

Cheers.

**Comment by rwood** [comment]
I've rewritten the code now.  tT shouldn't do that... but Windows 10 is now the preferred platform.
