### ISSUE TITLE
Transitions stop 1 frame before completing.

### ISSUE THREAD

**Issue by Nightfirecat** [rwood/WallpaperChange#9]
During the transition between time periods, the two frames will be blended as per the `transition_slices` directive, but after completing that many slices, the final frame is a mix between the second frame, and a mostly-transparent first frame.

It is very apparent with the 07-Night and 08-Late-Night frames in testing.

Here's an example, highlighting the moon between frames 07 and 08:

![frame blending error](http://i.imgur.com/sV7IOsS.png)

**Comment by rwood** [comment]
Fixed... plus a lot more.
